const Map countryNames = {
  "12": "USA",
  "16": "England",
  "6": "Indonesia",
  "43": "Germany",
  "4": "Philippines",
  "7": "Malaysia",
  "78": "France",
  "36": "Canada",
  "46": "Sweden",
  "47": "Norway",
  "77": "Kazakhstan",
  "351": "Portugal",
  "358": "Finland",
  "371": "Latvia",
  "372": "Estonia",
  "380": "Ukraine",
  "972": "Israel",
};

const Map servicesNames = {
  "tg": "Telegram",
  "fb": "Facebook",
  "ts": "Paypal",
  "ig": "Instagram",
  "oi": "Tinder",
  "nf": "Netflix",
  "ds": "Discord",
  "dh": "Ebay",
};
